#!/bin/bash
# Script per configurare le variabili d'ambiente per il deploy

echo "🔧 Baleno Website - Setup Variabili d'Ambiente"
echo "==============================================="
echo ""

echo "RAILWAY - Variabili d'ambiente necessarie per il backend:"
echo "--------------------------------------------------------"
echo ""
echo "DATABASE_URL: (Verrà configurato automaticamente quando aggiungi PostgreSQL)"
echo "JWT_SECRET: $(openssl rand -base64 32)"
echo "JWT_REFRESH_SECRET: $(openssl rand -base64 32)"
echo "JWT_EXPIRES_IN: 15m"
echo "JWT_REFRESH_EXPIRES_IN: 7d"
echo "NODE_ENV: production"
echo "PORT: 4000"
echo "FRONTEND_URL: https://baleno-website.vercel.app"
echo ""
echo "Opzionali:"
echo "SMTP_HOST: smtp.gmail.com"
echo "SMTP_PORT: 587"
echo "SMTP_USER: tua-email@gmail.com"
echo "SMTP_PASS: password-app-gmail"
echo "STRIPE_SECRET_KEY: sk_live_..."
echo "STRIPE_WEBHOOK_SECRET: whsec_..."
echo ""
echo "================================================"
echo ""
echo "VERCEL - Variabili d'ambiente necessarie per il frontend:"
echo "--------------------------------------------------------"
echo ""
echo "NEXT_PUBLIC_API_URL: https://baleno-website-production.up.railway.app/api"
echo ""
echo "Opzionali:"
echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_live_..."
echo ""
echo "================================================"
echo ""
echo "Come configurare su Railway:"
echo "1. Vai su railway.app e apri il tuo progetto"
echo "2. Clicca sul servizio backend"
echo "3. Vai su 'Variables'"
echo "4. Aggiungi le variabili sopra"
echo ""
echo "Come configurare su Vercel:"
echo "1. Vai su vercel.com e apri il tuo progetto"
echo "2. Vai su Settings > Environment Variables"
echo "3. Aggiungi NEXT_PUBLIC_API_URL"
echo "4. Rideploy il progetto"
